# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e42e1d6a7e21f7098e5b5fa9dda116c18e4118cd2a174eb52d6713017efa09c70aeeeace2ed6f6b010bb858c8a1695f7580204df2c64fb32e40853f5f7cc54

test:
  secret_key_base: 55c0925a644e04339e59d31691cf5e27de4ae2c860009923c4ffd5aa071078073efb44835ea3688fb6fcf34dd974c5dcf99fe496e71fe2a70dfc4a5b4b3361da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
